{% set name = "opentelemetry-instrumentation-aiopg" %}
{% set version = "0.53b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_aiopg-{{ version }}.tar.gz
  sha256: f2bfd99c090451a3a58ecb5b078d137dd8d51530e1bbb4e86aa254e7882c1b49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.53b1
    - opentelemetry-instrumentation ==0.53b1
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-semantic-conventions ==0.37b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-semantic-conventions ==0.38b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-semantic-conventions ==0.39b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-semantic-conventions ==0.40b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-semantic-conventions ==0.41b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-semantic-conventions ==0.42b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-semantic-conventions ==0.43b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-semantic-conventions ==0.44b0
    # - opentelemetry-instrumentation-aiopg 
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0
    # - aiopg <2.0.0,>=0.13.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiopg
  summary: OpenTelemetry aiopg instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
